-- KMD Hospital Patient Management System - Database Schema

-- Create PATIENTS table
CREATE TABLE PATIENTS_AT_KMD_HOSPITAL (
    PATIENT_ID NUMBER(4) CONSTRAINT PATIENT_ID_PK PRIMARY KEY,
    FIRST_NAME VARCHAR2(50),
    LAST_NAME VARCHAR2(50),
    DOB DATE,
    GENDER VARCHAR2(10),
    CONTACT_NUMBER VARCHAR2(15),
    EMAIL VARCHAR2(100)
);

-- Insert data into PATIENTS table
INSERT INTO PATIENTS_AT_KMD_HOSPITAL VALUES (1, 'Ali', 'Khan', TO_DATE('1992-04-10', 'YYYY-MM-DD'), 'Male', '555-1111', 'ali.khan@example.com');
INSERT INTO PATIENTS_AT_KMD_HOSPITAL VALUES (2, 'Zainab', 'Shah', TO_DATE('1988-11-20', 'YYYY-MM-DD'), 'Female', '555-2222', 'zainab.shah@example.com');
INSERT INTO PATIENTS_AT_KMD_HOSPITAL VALUES (3, 'Hasan', 'Raza', TO_DATE('1995-07-05', 'YYYY-MM-DD'), 'Male', '555-3333', 'hasan.raza@example.com');
INSERT INTO PATIENTS_AT_KMD_HOSPITAL VALUES (4, 'Mariam', 'Iqbal', TO_DATE('1990-02-15', 'YYYY-MM-DD'), 'Female', '555-4444', 'mariam.iqbal@example.com');

SELECT * FROM PATIENTS_AT_KMD_HOSPITAL;

------------------------------------------------------------

-- Create DOCTORS table
CREATE TABLE DOCTORS_AT_KMD_HOSPITAL (
    DOCTOR_ID NUMBER(4) CONSTRAINT DOCTOR_ID_PK PRIMARY KEY,
    FIRST_NAME VARCHAR2(50),
    LAST_NAME VARCHAR2(50),
    SPECIALIZATION VARCHAR2(50),
    CONTACT_NUMBER VARCHAR2(15)
);

-- Insert data into DOCTORS table
INSERT INTO DOCTORS_AT_KMD_HOSPITAL VALUES (2001, 'Dr. Sehrish', 'Abbas', 'Gynecologist', '555-7777');
INSERT INTO DOCTORS_AT_KMD_HOSPITAL VALUES (2002, 'Dr. Sana', 'Farooq', 'Dermatologist', '555-8888');
INSERT INTO DOCTORS_AT_KMD_HOSPITAL VALUES (2003, 'Dr. Bilal', 'Iqbal', 'Cardiologist', '555-9999');
INSERT INTO DOCTORS_AT_KMD_HOSPITAL VALUES (2004, 'Dr. Ahmed', 'Siddiqui', 'ENT Specialist', '555-0000');

SELECT * FROM DOCTORS_AT_KMD_HOSPITAL;

------------------------------------------------------------

-- Create APPOINTMENTS table
CREATE TABLE APPOINTMENTS_AT_KMD_HOSPITAL (
    APPOINTMENT_ID NUMBER(4) CONSTRAINT APPOINTMENT_ID_PK PRIMARY KEY,
    PATIENT_ID NUMBER(4),
    DOCTOR_ID NUMBER(4),
    APPOINTMENT_DATE DATE,
    REASON_FOR_VISIT VARCHAR2(100),
    FOREIGN KEY (PATIENT_ID) REFERENCES PATIENTS_AT_KMD_HOSPITAL(PATIENT_ID),
    FOREIGN KEY (DOCTOR_ID) REFERENCES DOCTORS_AT_KMD_HOSPITAL(DOCTOR_ID)
);

-- Insert data into APPOINTMENTS table
INSERT INTO APPOINTMENTS_AT_KMD_HOSPITAL VALUES (3001, 1001, 2001, TO_DATE('2025-06-01', 'YYYY-MM-DD'), 'General checkup');
INSERT INTO APPOINTMENTS_AT_KMD_HOSPITAL VALUES (3002, 1002, 2003, TO_DATE('2025-06-02', 'YYYY-MM-DD'), 'Skin allergy');
INSERT INTO APPOINTMENTS_AT_KMD_HOSPITAL VALUES (3003, 1003, 2002, TO_DATE('2025-06-04', 'YYYY-MM-DD'), 'Heart checkup');
INSERT INTO APPOINTMENTS_AT_KMD_HOSPITAL VALUES (3004, 1004, 2004, TO_DATE('2025-06-06', 'YYYY-MM-DD'), 'Ear pain');

SELECT * FROM APPOINTMENTS_AT_KMD_HOSPITAL;

------------------------------------------------------------

-- Create sequences for auto-generating IDs
CREATE SEQUENCE patient_id_seq START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE doctor_id_seq START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE appointment_seq START WITH 1 INCREMENT BY 1 NOCACHE;